export default {
    state:{
        footer_nav:[
            {
                name:'首页',
                name_code:'home',
                icon:'/static/tab-home.png',
                select_icon:'/static/tab-home-current.png',
                size:'small',
                number:0
            },
            {
                name:'分类',
                name_code:'category',
                icon:'/static/tab-cate.png',
                select_icon:'/static/tab-cate-current.png',
                size:'small',
                number:0
            },
            {
                name:'购物车',
                name_code:'cart',
                icon:'/static/tab-cart.png',
                select_icon:'/static/tab-cart-current.png',
                size:'small',
                number:0
            },
            {
                name:'我的',
                name_code:'user',
                icon:'/static/tab-my.png',
                select_icon:'/static/tab-my-current.png',
                size:'small',
                number:0
            },
        ],
        now_page_index:'home',
        navlist:[]
    },
    mutations:{
        change_nav_list(state,data){
            state.footer_nav = data;
        },
        change_page(state,index){
            state.now_page_index = index;
        },
        add_navlist(state,data){
            state.navlist.push(data);
        },
        cut_navlist(state){
            state.navlist.splice(-1);
        },
        set_number(state,data){
            state.footer_nav.forEach(it=>{
                if(it.name_code == 'cart'){
                    it.number = data;
                }
            });
        },
    },
    actions:{
        menu_2(ctx){
            let menu_list = [
                {
                    name:'首页',
                    name_code:'home',
                    icon:'/static/tab-home.png',
                    select_icon:'/static/tab-home-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'分类',
                    name_code:'category',
                    icon:'/static/tab-cate.png',
                    select_icon:'/static/tab-cate-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'我的店铺',
                    name_code:'shop',
                    icon:'/static/tab-shop.png',
                    select_icon:'/static/tab-shop-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'购物车',
                    name_code:'cart',
                    icon:'/static/tab-cart.png',
                    select_icon:'/static/tab-cart-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'我的',
                    name_code:'user',
                    icon:'/static/tab-my.png',
                    select_icon:'/static/tab-my-current.png',
                    size:'small',
                    number:0
                },
            ]
            ctx.commit("change_nav_list",menu_list)
            ctx.commit("change_page",'shop')
        },
        menu_3(ctx){
            let menu_list = [
                {
                    name:'首页',
                    name_code:'home',
                    icon:'/static/tab-home.png',
                    select_icon:'/static/tab-home-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'分类',
                    name_code:'category',
                    icon:'/static/tab-cate.png',
                    select_icon:'/static/tab-cate-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'建店',
                    name_code:'shop',
                    icon:'/static/tab-shop.png',
                    select_icon:'/static/tab-shop-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'购物车',
                    name_code:'cart',
                    icon:'/static/tab-cart.png',
                    select_icon:'/static/tab-cart-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'我的',
                    name_code:'user',
                    icon:'/static/tab-my.png',
                    select_icon:'/static/tab-my-current.png',
                    size:'small',
                    number:0
                },
            ]
            ctx.commit("change_nav_list",menu_list)
            ctx.commit("change_page",'home')
        },
        menu_4(ctx){
            let menu_list = [
                {
                    name:'首页',
                    name_code:'home',
                    icon:'/static/tab-home.png',
                    select_icon:'/static/tab-home-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'分类',
                    name_code:'category',
                    icon:'/static/tab-cate.png',
                    select_icon:'/static/tab-cate-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'我的店铺',
                    name_code:'shop',
                    icon:'/static/tab-shop.png',
                    select_icon:'/static/tab-shop-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'购物车',
                    name_code:'cart',
                    icon:'/static/tab-cart.png',
                    select_icon:'/static/tab-cart-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'我的',
                    name_code:'user',
                    icon:'/static/tab-my.png',
                    select_icon:'/static/tab-my-current.png',
                    size:'small',
                    number:0
                },
            ]
            ctx.commit("change_nav_list",menu_list)
        },
        menu_5(ctx){
            let menu_list = [
                {
                    name:'首页',
                    name_code:'home',
                    icon:'/static/tab-home.png',
                    select_icon:'/static/tab-home-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'分类',
                    name_code:'category',
                    icon:'/static/tab-cate.png',
                    select_icon:'/static/tab-cate-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'购物车',
                    name_code:'cart',
                    icon:'/static/tab-cart.png',
                    select_icon:'/static/tab-cart-current.png',
                    size:'small',
                    number:0
                },
                {
                    name:'我的',
                    name_code:'user',
                    icon:'/static/tab-my.png',
                    select_icon:'/static/tab-my-current.png',
                    size:'small',
                    number:0
                },
            ]
            ctx.commit("change_nav_list",menu_list)
        },
    }
}